### PR TITLE
Support markdown format in description text

### PR DESCRIPTION
**Pull request by otterdahl**
I suggest adding support for markdown format in the description text. This allows more advanced formatting which will be shown in the online doc and pdf. Markdown is converted to RST (with sxl-tools) in the sxl repo.

This PR adds a link to the wiki in S0033 and updates the format of the table to markdown format (it used to be rst format)

### CODE REVIEW

**Comment by emiltin** [comment]
is this a suggestion for changing the description of S0033? or a more general change?

**Comment by otterdahl** [comment]
I think it is useful to support markdown in general. This PR only adds this specific link (and updates the format of the table), but I could imagine adding some markdown in description for other alarms/commands/status in the future if it makes sense. What do you think?

**Comment by emiltin** [comment]
Without having looked deeper into this, i think it would be great if we could converge on a single format, so we don't need to convert between them. RTS does the job good, but the syntax is a bit esoteric. Markdown is nice, but perhaps not for writing extensive documentation and has different incompatible variations. Did you look into asciidocs?

**Comment by otterdahl** [comment]
* The RST is not very pretty, and it´s easy to make mistakes. But it is very feature complete and it is possible to make sure it looks good with online doc as well as pdf.
* Markdown is simple. But it needs extensions to support some features. I did experiment with markdown in sphinx, which is possible. But it needs a tool called Myst which extends the markdown format. However, we use other secions of the sxl (coordination for instace, which contains directives that makes sure it looks good in PDF). The end result was not much better that just keeping RST. It is however possible to convert from markdown to rst with `sxl2rst.py` (sxl-tools)
* Asciidocs seems like a good choice for printed documentation. It also have support for sphinx, but [it has issues](https://pypi.org/project/sphinx-asciidoc/).

I can see a few alternatives:
1. Do not support any markup language in the SXL. It keeps things simple
2. Allow some **RST** markup in the SXL descriptions, for instance for adding links 
    * No special conversion is necessary in `sxl2rst.py` (sxl-tools). It already works since sphinx (with rst) is used in rsmp_sxl_traffic_lights
2. Allow some **markdown**  in **asciidocs** the SXL descriptions
     * `sxl2rst.py` needs to updated to do conversion to rst using pandoc (PR for [this exists here](https://github.com/rsmp-nordic/sxl-tools/pull/38))
3. Convert the [rsmp_sxl_rsmp_lights](https://github.com/rsmp-nordic/rsmp_sxl_traffic_lights) from sphinx/rst to markdown or asciidocs, but that is a major work and tradeoffs apply according the comparisons mentioned above.

**Comment by emiltin** [comment]
I think good documentatiojn requires tables, links, etc. So I'm in favour of allowing markup in the descriptions in the YAML.  An alternative would be to keep descriptions with markup as separate files, but I think it would complicate things too much.

There are some converters for RTS->Asciidocs, but I have no idea about the quality.

Long-term, asciidocs might be better than markdown for documentation. But the simplest right now might be to allow markdown in the YAML.

**Comment by otterdahl** [comment]
If it is OK with you I can merge this PR. We can consider switching markup language in the future

**Comment by emiltin** [comment]
should we convert all tables to markdown?

**Comment by otterdahl** [comment]
> should we convert all tables to markdown?

There is only one in sxl.yaml (included in this PR). If you refer to other parts of the SXL, then no. I don't think it is worth the trouble at this point.

**Comment by emiltin** [comment]
merged

**Pull request merged**
